import { SectionType } from "./types";

export const SECTION_CONFIGS: Record<
  SectionType,
  { label: string; icon: string; defaultData: () => Record<string, unknown> }
> = {
  navbar: {
    label: "Navigation",
    icon: "bi-layout-text-sidebar-reverse",
    defaultData: () => ({
      logo: "MonSite",
      logoImageUrl: "",
      logoImageWidth: 120,
      logoImageHeight: 40,
      navBgType: "color",
      navBgColor: "#ffffff",
      navBgImageUrl: "",
      navBgImageOpacity: 1,
      navBgImageSize: "cover",
      navBgImagePosition: "center",
      navBgImageBlur: 0,
      navBgColorType: "solid",
      navBgGradientCode: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      links: [
        { label: "Accueil", type: "section", href: "#hero" },
        { label: "Services", type: "section", href: "#expertises" },
        { label: "À propos", type: "page", href: "/a-propos" },
        { label: "Contact", type: "section", href: "#contact" },
      ],
      linksColor: "#334155",
      linksFontSize: "0.88rem",
      linksFontWeight: "600",
      linksFontStyle: "normal",
      cta1Text: "Planifier un appel",
      cta1Url: "#contact",
      cta1Enabled: true,
      cta1Color: "#334155",
      cta1FontSize: ".85rem",
      cta1Icon: "",
      cta1Size: "md",
      cta1BorderColor: "#E2E8F0",
      cta1TextColor: "#334155",
      cta2Text: "Nous contacter",
      cta2Url: "#contact",
      cta2Enabled: true,
      cta2Color: "#2563EB",
      cta2BorderColor: "",
      cta2TextColor: "#fff",
      cta2FontSize: ".85rem",
      cta2Icon: "",
      cta2Size: "md",
    }),
  },
  hero: {
    label: "Hero / Bannière",
    icon: "bi-layout-text-window-reverse",
    defaultData: () => ({
      badge: "NOTRE AGENCE",
      title: "Titre principal\nde votre page",
      subtitle: "Description courte de votre offre ou service principal.",
      cta1Text: "Commencer →",
      cta1Url: "#contact",
      cta2Text: "En savoir plus",
      cta2Url: "#",
      rating: "4.9/5",
      ratingLabel: "sur Google",
      stats: ["+100 projets", "Certifié Expert"],
      clients: ["Client 1", "Client 2", "Client 3"],
      imageUrl: "",
    }),
  },
  expertises: {
    label: "Services / Expertises",
    icon: "bi-grid",
    defaultData: () => ({
      sectionLabel: "NOS SERVICES",
      title: "Nos expertises au service de votre projet",
      subtitle: "Notre équipe maîtrise les meilleures technologies.",
      bgColor: "#0F172A",
      items: [
        { icon: "bi-laptop", label: "Développement Web" },
        { icon: "bi-palette", label: "Design UI/UX" },
        { icon: "bi-phone", label: "Applications Mobile" },
        { icon: "bi-graph-up-arrow", label: "SEO & Marketing" },
      ],
      ctaText: "Voir tous nos services",
    }),
  },
  temoignages: {
    label: "Témoignages",
    icon: "bi-chat-quote",
    defaultData: () => ({
      sectionLabel: "ILS NOUS FONT CONFIANCE",
      title: "Ce que disent nos clients",
      subtitle: "La satisfaction de nos clients est notre priorité.",
      items: [
        {
          logo: "Client A",
          logoColor: "#2563EB",
          name: "Jean Martin",
          role: "Directeur",
          text: "Excellent travail, équipe très professionnelle et réactive.",
        },
        {
          logo: "Client B",
          logoColor: "#0F172A",
          name: "Marie Dupont",
          role: "PDG",
          text: "Notre projet a été livré dans les délais avec une qualité remarquable.",
        },
      ],
    }),
  },
  realisations: {
    label: "Réalisations / Portfolio",
    icon: "bi-images",
    defaultData: () => ({
      sectionLabel: "NOS RÉALISATIONS",
      title: "Nos projets récents",
      ctaText: "Voir toutes nos réalisations →",
      items: [
        {
          titre: "Projet Alpha",
          desc: "Description du projet.",
          bg: "#1A1A1A",
          color: "#C6A96A",
          imageUrl: "",
        },
        {
          titre: "Projet Beta",
          desc: "Description du projet.",
          bg: "#F5F0EB",
          color: "#2D2D2D",
          imageUrl: "",
        },
      ],
    }),
  },
  blog: {
    label: "Blog / Articles",
    icon: "bi-newspaper",
    defaultData: () => ({
      sectionLabel: "NOS PUBLICATIONS",
      title: "Nos derniers articles",
      ctaText: "Voir tous les articles →",
      items: [
        {
          tag: "ACTUALITÉ",
          titre: "Premier article du blog",
          desc: "Description courte du premier article.",
          imageUrl: "",
          imageBg: "#EFF6FF",
          imageEmoji: "📝",
        },
        {
          tag: "TUTORIEL",
          titre: "Deuxième article",
          desc: "Description courte du deuxième article.",
          imageUrl: "",
          imageBg: "#F0FDF4",
          imageEmoji: "💡",
        },
      ],
    }),
  },
  faq: {
    label: "FAQ",
    icon: "bi-question-circle",
    defaultData: () => ({
      sectionLabel: "QUESTIONS FRÉQUENTES",
      title: "Vos questions, nos réponses",
      items: [
        {
          question: "Comment se passe le premier contact ?",
          answer:
            "Nous organisons un appel découverte gratuit pour comprendre votre projet et vos besoins.",
        },
        {
          question: "Quels sont vos délais de livraison ?",
          answer:
            "Selon la complexité du projet, comptez entre 4 et 12 semaines.",
        },
      ],
    }),
  },
  cta: {
    label: "Appel à l'action",
    icon: "bi-megaphone",
    defaultData: () => ({
      sectionLabel: "PASSEZ À L'ACTION",
      title: "Démarrez votre projet\ndès aujourd'hui",
      subtitle: "Contactez-nous pour un audit gratuit de votre projet.",
      bgColor: "#0F172A",
      cta1Text: "Démarrer un projet",
      cta1Url: "#contact",
      cta1Color: "#2563EB",
      cta2Text: "Planifier un appel →",
      cta2Url: "#",
    }),
  },
  contact: {
    label: "Contact",
    icon: "bi-envelope",
    defaultData: () => ({
      sectionLabel: "CONTACTEZ-NOUS",
      title: "Parlons de votre projet",
      subtitle:
        "Remplissez le formulaire et nous vous répondrons dans les 24h.",
      bgColor: "#F8FAFC",
      email: "contact@monsite.com",
      phone: "+33 1 45 67 89",
      address: "Paris, France",
      labelNom: "Votre nom",
      labelEmail: "Votre email",
      labelMessage: "Votre message",
      labelSubmit: "Envoyer le message",
    }),
  },
  footer: {
    label: "Pied de page",
    icon: "bi-layout-bottom",
    defaultData: () => ({
      logo: "MonSite",
      cities: ["Paris", "Remote"],
      columns: [
        {
          title: "SERVICES",
          links: ["Développement Web", "Design UI/UX", "SEO"],
        },
        { title: "SITE", links: ["Accueil", "À propos", "Contact"] },
      ],
      copyright: `© ${new Date().getFullYear()} MonSite · Tous droits réservés`,
      bgColor: "#0F172A",
    }),
  },
};
